### ISSUE TITLE
Michel Olagnon's name misspelled in About section

### ISSUE THREAD

**Issue by Beliavsky** [urbanjost/f90split#1]
It's correct in the Readme.

**Comment by urbanjost** [comment]
Oops. Should be good now.  Original site seems to be gone so thought this might be useful for others. I had this (modified, but I do not think much)  version I still use I thought others might find useful.  There is at least one other program with similar features (Burkhardt?) but this one is freely licensed and I have used it successfully multiple times.  I usually keep an original of anything I pick up but I did not have my typical Archive directory for this one, and quite surprisingly could not find the original or his f90ppr program, etc. 

Playing around with a fpm-tools(1) tool as a plugin for fpm as a concept so stuck a couple of programs on my repo and gave them topic "fpm-tools" and this seemed a good candidate.  Not generic, but on my machine I can enter "fpm tools f90split" or
"fpm tools prep"  and do a clone, build, and default installation of that particular program.  A github search does not appear to require an exact match on topics so the search did not quite do what I want if all of github is searched; etc.

Scanned the rest and it looks OK elsewhere, so I think you can close
 ```bash
#!/bin/bash
#@(#) fpm-tools  plugin for fpm on Ubuntu to install my fpm-tools repositories
if [ "$*" = '' ]
then
   xdg-open 'https://github.com/search?q=user%3Aurbanjost%20in:topic%20fpm-tools'
   exit
fi
for NAME in $*
do
   trap "rm -f -- '/tmp/${SCRATCH:-NOTTHERE}'" EXIT
   SCRATCH=scr_$(uuidgen)
   mkdir -p /tmp/$SCRATCH
   cd /tmp/$SCRATCH || exit
   git clone https://github.com/urbanjost/$NAME
   cd $NAME || exit
   fpm install
   $NAME --help|less -r
done
exit
```
